DROP DATABASE IF EXISTS CONTACTANOS2;
CREATE DATABASE CONTACTANOS2;
USE CONTACTANOS2;

CREATE TABLE PERSONA(
id INT(10) PRIMARY KEY NOT NULL,
nombre VARCHAR(25) NOT NULL,
email VARCHAR(25) NOT NULL,
ubicacion VARCHAR(25) NOT NULL,
hora VARCHAR(25) NOT NULL,
dia VARCHAR(25) NOT NULL,
mes VARCHAR(25) NOT NULL,
año VARCHAR(25) NOT NULL,
evento VARCHAR(25) NOT NULL
);
INSERT INTO PERSONA VALUES('','nelly','arenasnelly@gmail.cm','av venustiano carranza','3 pm','3','Abril','2020','cumpleaños');